spring:
  application:
    name: pay-pilot-kyc
  datasource:
    url: jdbc:postgresql://localhost:5432/paypilot_kyc
    username: postgres
    password: Subbu@141
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
      enabled: true
server:
  port: 8081
  servlet:
    context-path: /paypilot
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
